ApplicationPerformance/Models/Objective.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplicationPerformance.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Objective
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Objective()
    {

        this.Goals = new HashSet<Goal>();

    }


    public int ObjectiveID { get; set; }

    public string Title { get; set; }

    public string ObjectiveDescription { get; set; }

    public Nullable<ObjectiveType> ObjectiveType { get; set; }

    public Nullable<Confidentiality> Confidentiality { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Goal> Goals { get; set; }

}

}

ApplicationPerformance/Models/ObjectiveType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplicationPerformance.Models
{

using System;
    

public enum ObjectiveType : int
{

    Training = 0,

    General = 1,

    Long_term = 2,

}

}

ApplicationPerformance/Controllers/ObjectivesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApplicationPerformance.Models;

namespace ApplicationPerformance.Controllers
{
    public class ObjectivesController : Controller
    {
        private DatabasePMEntities db = new DatabasePMEntities();

        // GET: Objectives
        public ActionResult Index()
        {
            return View(db.Objectives.ToList());
        }

        // GET: Objectives/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objective objective = db.Objectives.Find(id);
            if (objective == null)
            {
                return HttpNotFound();
            }
            return View(objective);
        }

        // GET: Objectives/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Objectives/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ObjectiveID,Title,ObjectiveDescription,ObjectiveType,Confidentiality")] Objective objective)
        {
            if (ModelState.IsValid)
            {
                db.Objectives.Add(objective);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(objective);
        }

        // GET: Objectives/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objective objective = db.Objectives.Find(id);
            if (objective == null)
            {
                return HttpNotFound();
            }
            return View(objective);
        }

        // POST: Objectives/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ObjectiveID,Title,ObjectiveDescription,ObjectiveType,Confidentiality")] Objective objective)
        {
            if (ModelState.IsValid)
            {
                db.Entry(objective).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(objective);
        }

        // GET: Objectives/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objective objective = db.Objectives.Find(id);
            if (objective == null)
            {
                return HttpNotFound();
            }
            return View(objective);
        }

        // POST: Objectives/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Objective objective = db.Objectives.Find(id);
            db.Objectives.Remove(objective);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApplicationPerformance/Views/Objectives/Create.cshtml
@model ApplicationPerformance.Models.Objective

@{
    Layout = null;
}
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@using (Html.BeginForm("Create", "Objectives", "POST"))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>EmployeeModel</legend>
        <table width="100%">
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Objective</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ObjectiveDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ObjectiveDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ObjectiveDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ObjectiveType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.ObjectiveType, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ObjectiveType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Confidentiality, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Confidentiality, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Confidentiality, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
            }

            @*<div>
                @Html.ActionLink("Back to List", "Index")
            </div>*@
        </table>
    </fieldset>
}

ApplicationPerformance/Views/Objectives/Delete.cshtml
@model ApplicationPerformance.Models.Objective

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Objective</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObjectiveDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObjectiveDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObjectiveType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObjectiveType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Confidentiality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Confidentiality)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApplicationPerformance/Views/Objectives/Details.cshtml
S@model ApplicationPerformance.Models.Objective

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Objective</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObjectiveDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObjectiveDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObjectiveType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObjectiveType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Confidentiality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Confidentiality)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ObjectiveID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ApplicationPerformance/Views/Objectives/Edit.cshtml
@model ApplicationPerformance.Models.Objective

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Objective</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ObjectiveID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ObjectiveDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ObjectiveDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ObjectiveDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ObjectiveType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ObjectiveType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ObjectiveType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Confidentiality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Confidentiality, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Confidentiality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplicationPerformance/Views/Objectives/Index.cshtml
@model IEnumerable<ApplicationPerformance.Models.Objective>

@{
    ViewBag.Title = "Index";
}

<link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.20.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $("#ADDObjective").live("click", function (e) {
            var url = $(this).attr('href');
            $("#dialog-edit").dialog({
                title: 'Add New Objective',
                autoOpen: false,
                resizable: false,
                height: 455,
                width: 550,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                open: function (event, ui) {
                    $(this).load(url);

                },
                close: function (event, ui) {
                    $(this).dialog('close');
                }
            });

            $("#dialog-edit").dialog('open');
            return false;
        });
<h2>Index</h2>
        <b>
    <a id="ADDObjective" href="..\SystemUsers\Create">Add New Objective</a></b>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ObjectiveDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ObjectiveType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Confidentiality)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ObjectiveDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ObjectiveType).ToString().Replace("_", " ")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Confidentiality)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ObjectiveID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ObjectiveID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ObjectiveID })
        </td>
    </tr>
}

</table>