ApplicationPerformance/Models/Evaluation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplicationPerformance.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Evaluation
{

    public int EvaluationID { get; set; }

    public Nullable<Rating> Rating { get; set; }

    public int SystemUserID { get; set; }

    public System.DateTime EvaluationDate { get; set; }

    public Nullable<int> CompleteObjectives { get; set; }

    public Nullable<int> TotalObjectives { get; set; }

    public string ManagerComment { get; set; }

    public string EmployeeComment { get; set; }



    public virtual SystemUser SystemUser { get; set; }

}

}

ApplicationPerformance/Controllers/EvaluationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApplicationPerformance.Models;
using System.Web.Helpers;


namespace ApplicationPerformance.Controllers
{
    public class EvaluationsController : Controller
    {
        private DatabasePMEntities db = new DatabasePMEntities();

        //Testing new code


        #region Old index method
        //public ActionResult Index()
        //{
        //    SystemUser user = (SystemUser)Session["CurrentUser"];

        //    ViewBag.evalLastName = user.LastName;
        //    ViewBag.evalFirstName = user.FirstName;
        //    var evaluations = db.Evaluations.Include(e => e.SystemUser);


        //    evaluations = evaluations.Where(a => a.SystemUser.SystemUserID.Equals(user.SystemUserID));
        //    var systemusers = from a in db.SystemUsers //grabs all users currently in the database
        //                      select a;

        //    systemusers = systemusers.Where(a => a.LastName.Equals(user.AssignedManager));
        //    SystemUser assignedmanager = (SystemUser)systemusers.First();

        //    ViewBag.AssignedManagerID = assignedmanager.SystemUserID;
        //    ViewBag.EvalID = user.SystemUserID;

        //    return View(evaluations.ToList());

        //}

        //Added chart to evaluation method 
        #endregion



        #region Individual Employee's evaluations
        int Jan;
        int Feb;
        int Mar;
        int Apr;
        int May;
        int Jun;
        int Jul;
        int Aug;
        int Sep;
        int Oct;
        int Nov;
        int Dec;

        int janEvaluationsValue;
        int janEvaluationsCount;

        int febEvaluationsValue;
        int febEvaluationsCount;

        int marEvaluationsValue;
        int marEvaluationsCount;


        int aprEvaluationsValue;
        int aprEvaluationsCount;

        int mayEvaluationsValue;
        int mayEvaluationsCount;

        int junEvaluationsValue;
        int junEvaluationsCount;

        int julEvaluationsValue;
        int julEvaluationsCount;

        int augEvaluationsValue;
        int augEvaluationsCount;

        int sepEvaluationsValue;
        int sepEvaluationsCount;

        int octEvaluationsValue;
        int octEvaluationsCount;

        int novEvaluationsValue;
        int novEvaluationsCount;

        int decEvaluationsValue;
        int decEvaluationsCount;
        #endregion

        #region All employee evaluations variables
        int empJan;
        int empFeb;
        int empMar;
        int empApr;
        int empMay;
        int empJun;
        int empJul;
        int empAug;
        int empSep;
        int empOct;
        int empNov;
        int empDec;

        int empJanEvaluationsValue;
        int empJanEvaluationsCount;

        int empFebEvaluationsValue;
        int empFebEvaluationsCount;

        int empMarEvaluationsValue;
        int empMarEvaluationsCount;


        int empAprEvaluationsValue;
        int empAprEvaluationsCount;

        int empMayEvaluationsValue;
        int empMayEvaluationsCount;

        int empJunEvaluationsValue;
        int empJunEvaluationsCount;

        int empJulEvaluationsValue;
        int empJulEvaluationsCount;

        int empAugEvaluationsValue;
        int empAugEvaluationsCount;

        int empSepEvaluationsValue;
        int empSepEvaluationsCount;

        int empOctEvaluationsValue;
        int empOctEvaluationsCount;

        int empNovEvaluationsValue;
        int empNovEvaluationsCount;

        int empDecEvaluationsValue;
        int empDecEvaluationsCount;

        #endregion





        // GET: Evaluations
        public ActionResult Index(string searchString, DateTime? start, DateTime? end)

        {
            SystemUser user = (SystemUser)Session["CurrentUser"];

            ViewBag.evalLastName = user.LastName;
            ViewBag.evalFirstName = user.FirstName;
            var evaluations = db.Evaluations.Include(e => e.SystemUser);

            #region Specfic employee's evaluation

            if (Session["CurrentUser"] != null)
            {
                //  user = (SystemUser)Session["CurrentUser"];//assigns the logged in user's details
                //Grabs all the user's appraisals
                if (start == null || end == null)
                {

                    evaluations = evaluations.Where(a => a.SystemUser.SystemUserID.Equals(user.SystemUserID));
                }
                else
                {
                    evaluations = evaluations
                                       .Where(x =>
                                        x.EvaluationDate >= start
                                       && x.EvaluationDate <= end
                                       && x.SystemUser.SystemUserID.Equals(user.SystemUserID))
                                       .OrderByDescending(x => x.EvaluationID)
                                       ;
                }

            }

            //searching functionality
            if (!String.IsNullOrEmpty(searchString)) //allowing to search using either first or last name
            {//The search string value is received from a text box that you'll add to the Index view.

                evaluations = evaluations.Where(a => /*a.Appraisal.AppraisalEndDate.ToString().Contains(searchString)   //filter by date*/
                                         a.ManagerComment.ToUpper().Contains(searchString)
                                        );
            }


            //evaluations = evaluations.Where(a => a.SystemUser.SystemUserID.Equals(user.SystemUserID));
            var systemusers = from a in db.SystemUsers //grabs all users currently in the database
                              select a;

            systemusers = systemusers.Where(a => a.LastName.Equals(user.AssignedManager));
            SystemUser assignedmanager = (SystemUser)systemusers.First();

            ViewBag.AssignedManagerID = assignedmanager.SystemUserID;
            ViewBag.EvalID = user.SystemUserID;



            // goodEvaluations = goodEvaluations.Where(a => a.Rating.Equals(ApplicationPerformance.Models.Rating.Good));
            foreach (var item in evaluations)
            {

                if (item.EvaluationDate.Month == 1)
                {
                    if (item.Rating.ToString().ToUpper() == "GOOD")
                    {
                        janEvaluationsValue += 3;
                        janEvaluationsCount += 1;
                    }
                    if (item.Rating.ToString().ToUpper() == "AVERAGE")
                    {
                        janEvaluationsValue += 2;
                        janEvaluationsCount += 1;
                    }
                    if (item.Rating.ToString().ToUpper() == "POOR")
                    {
                        janEvaluationsValue += 1;
                        janEvaluationsCount += 1;
                    }
                    Jan = janEvaluationsValue / janEvaluationsCount;


                    ViewBag.Jan = Jan;
                }


                else if (item.EvaluationDate.Month == 2)
                {
                    if (item.Rating.ToString().ToUpper() == "GOOD")
                    {
                        febEvaluationsValue += 3;
                        febEvaluationsCount += 1;
                    }
                    if (item.Rating.ToString().ToUpper() == "AVERAGE")
                    {
                        febEvaluationsValue += 2;
                        febEvaluationsCount += 1;
                    }
                    if (item.Rating.ToString().ToUpper() == "POOR")
                    {
                        febEvaluationsValue += 1;
                        febEvaluationsCount += 1;
                    }
                    Feb = febEvaluationsValue / febEvaluationsCount;


                    ViewBag.Feb = Feb;

                }


                else if (item.EvaluationDate.Month == 3)
                {
                    if (item.Rating.ToString().ToUpper() == "GOOD")
                    {
                        marEvaluationsValue += 3;
                        marEvaluationsCount += 1;
                    }
                    if (item.Rating.ToString().ToUpper() == "AVERAGE")
                    {
                        marEvaluationsValue += 2;
                        marEvaluationsCount += 1;
                    }
                    if (item.Rating.ToString().ToUpper() == "POOR")
                    {
                        marEvaluationsValue += 1;
                        marEvaluationsCount += 1;
                    }
                    Mar = marEvaluationsValue / marEvaluationsCount;

                    ViewBag.Mar = Mar;

                }



                else if (item.EvaluationDate.Month == 4)
                {
                    if (item.Rating.ToString().ToUpper() == "GOOD")
                    {
                        aprEvaluationsValue += 3;
                        aprEvaluationsCount += 1;
                    }
                    if (item.Rating.ToString().ToUpper() == "AVERAGE")
                    {
                        aprEvaluationsValue += 2;
                        aprEvaluationsCount += 1;
                    }
                    if (item.Rating.ToString().ToUpper() == "POOR")
                    {
                        aprEvaluationsValue += 1;
                        aprEvaluationsCount += 1;
                    }
                    Apr = aprEvaluationsValue / aprEvaluationsCount;

                    ViewBag.Apr = Apr;

                }


                else if (item.EvaluationDate.Month == 5)
                {
                    if (item.Rating.ToString().ToUpper() == "GOOD")
                    {
                        mayEvaluationsValue += 3;
                        mayEvaluationsCount += 1;
                    }

ApplicationPerformance/Views/Evaluations/Create.cshtml
@model ApplicationPerformance.Models.Evaluation

@{
    ViewBag.Title = "Create";
}

<br />

<h2>Evaluate @ViewBag.FirstName @ViewBag.LastName </h2>


<div class="row">
    <div class="col-md-3">

    </div>

    <div class="col-md-6">

    <div style="border:5px solid #266f91; background-color:#266f91; height: 120px; width:120px; border-radius:100px; text-align:center;" class="obj-num-display">
        <p style="color:white;text-align:center;"><strong> 
           Complete Objectives: @ViewBag.CompleteGoals
            
            </strong></p>
    </div>

    <div style="border:5px solid #60c3ad; background-color:#60c3ad; height: 120px; width:120px; border-radius:100px; text-align:center;" class="obj-num-display">
        <p><strong>
            Total Objectives: @ViewBag.TotalGoals
              
            </strong></p>
    </div>
        <div class="col-md-3">

        </div>
 </div>

    </div>

        <button class="btn btn-searching" style="margin-bottom:10px; margin-left:10px; color:white; background-color:#266f91; border:none; padding:5px; border-radius:2px;" onclick="location.href='@Url.Action("Index", "Evaluations")'">Evaluations History</button>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
               
             
                <div class="form-group" style="align-items:center; background-color:azure">
                    <br />



                    <h4 style="text-align:center">Incomplete Objectives</h4>
                    @foreach (var item in ViewBag.InCompleteGoalsList)
                    {
                      <p style="text-align:center"> @item </p> 

                    }
                    <br />
                </div>

                <div class="row" >

                    <div class="col-md-3">

                    </div>


                    <div class="col-md-3">
                        @*@Html.LabelFor(model => model.ManagerComment, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        <h4 style="text-align:left">Manager Comments</h4>
                            @Html.EditorFor(model => model.ManagerComment, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ManagerComment, "", new { @class = "text-danger" })
                    </div>

                

                    <div class="col-md-6">
                        @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10" style="margin-bottom:15px">
                            @Html.EnumDropDownListFor(model => model.Rating, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
                        </div>
                        
                        @Html.LabelFor(model => model.EvaluationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EvaluationDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EvaluationDate, "", new { @class = "text-danger" })
                        </div>

                    </div>


                </div>
                
            </div>



    @*<h4>Evaluation</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @*<div class="form-group">
            @Html.LabelFor(model => model.SystemUserID, "Employee", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SystemUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SystemUserID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
       
    </div>

    <div class="form-group">
      
    </div>

        <div class="row">
            @*<button class="btn btn-searching" style="margin-bottom:10px; margin-left:10px; color:white; background-color:#266f91; border:none; padding:5px; border-radius:2px;" onclick="location.href='@Url.Action("SelectedEmployee", "Goals", new { id = @ViewBag.EvalID })'">Back to Employee Page</button>*@
           <div class="col-md-1">

             <button class="btn btn-searching" style="margin-bottom:10px; margin-left:10px; color:white; background-color:#266f91; border:none; padding:5px; border-radius:2px;" onclick="location.href='@Url.Action("ManagerEmployees", "SystemUsers", new { id = @ViewBag.AssignedManagerID })'">Back to Dashboard</button>
               
            </div>
            
            <div class="col-md-10">

            </div>

             <div class="col-md-1">
                 
                    @*<input type="submit" value="Create" class="btn btn-searching" />*@
                 @*<div class="form-group">*@
                     <div class="col-md-offset-2 col-md-10">
                         <input type="submit" value="Create" class="btn btn-searching" />
                     </div>
                 </div>

                </div>
            @*</div>*@

@*<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Create" class="btn btn-searching" />
    </div>
</div>*@

        }

ApplicationPerformance/Views/Evaluations/Delete.cshtml
@model ApplicationPerformance.Models.Evaluation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evaluation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EvaluationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EvaluationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompleteObjectives)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompleteObjectives)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalObjectives)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalObjectives)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerComment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerComment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeComment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeComment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SystemUser.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SystemUser.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApplicationPerformance/Views/Evaluations/Details.cshtml
@model ApplicationPerformance.Models.Evaluation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Evaluation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EvaluationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EvaluationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompleteObjectives)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompleteObjectives)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalObjectives)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalObjectives)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerComment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerComment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeComment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeComment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SystemUser.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SystemUser.LastName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EvaluationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ApplicationPerformance/Views/Evaluations/Edit.cshtml
@model ApplicationPerformance.Models.Evaluation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Evaluation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EvaluationID)

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Rating, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SystemUserID, "SystemUserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SystemUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SystemUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EvaluationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EvaluationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EvaluationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompleteObjectives, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompleteObjectives, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompleteObjectives, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalObjectives, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalObjectives, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalObjectives, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerComment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerComment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerComment, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeComment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeComment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeComment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplicationPerformance/Views/Evaluations/Index.cshtml
@model IEnumerable<ApplicationPerformance.Models.Evaluation>
@{
    ViewBag.Title = "Index";
}


<h2>Evaluations for @ViewBag.evalFirstName @ViewBag.evalLastName </h2>

<br />

<br />

<table class="table">
    <tr>
        @*<th>
                <img src="@Url.Action("MyChart")" alt="SimpleChart" />
            </th>
            <th>
                <img src="/Content/Pictures/RatingKey.png" />
            </th>*@
        <div id="chartContainer3"></div>
    </tr>
</table>

@using (Html.BeginForm())
{<table class="table">
        <tr>
            <p>
                Find by objective title, type or appraisal end date: @Html.TextBox("SearchString")


                @*<input class="btn btn-searching" type="submit" value="Search" />*@


            </p>


            <div class="form-horizontal">
                <div class="form-group form-group-sm">
                    <div class="col-md-8">
                        <p>  Start Date: @Html.TextBox("start", null, new { @class = "form-control datepicker" })</p>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <div class="col-md-8">
                        <p>  End Date:@Html.TextBox("end", null, new { @class = "form-control datepicker" })</p>
                    </div>
                </div>
                <div class="form-group-sm">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" /> <span> </span>
                    </div>
                </div>
            </div>
    </table>
}



<script type="text/javascript">

    window.onload = function () {
        var chart3 = new CanvasJS.Chart("chartContainer3", {
            title: {
                text: "Evaluation Averages"
            },
            animationEnabled: true,

            axisY: {
                title: "Employee's Rating",
                includeZero: false,
                suffix: " ",
                lineColor: "#369EAD"
            },
            axisY2: {
                title: "All Employees' Ratings",
                includeZero: false,
                suffix: " ",
                lineColor: "#C24642"
            },
            axisX: {
                title: "Months",
                suffix: ""
            },
            data: [
            {
                type: "spline",
                name: "Speed",
                dataPoints: [
                 { x: 1, y: @ViewBag.Jan },
                { x: 2, y: @ViewBag.Feb },
                { x: 3, y: @ViewBag.Mar},
                { x: 4, y: @ViewBag.Apr },
                { x: 5, y: @ViewBag.May },
                { x: 6, y: @ViewBag.Jun  },
                { x: 7, y: @ViewBag.Jul  },
                { x: 8, y: @ViewBag.Aug },
                { x: 9, y: 2  },
                { x: 10, y: 2  },
                { x: 11, y: 3 },
                { x: 12, y: 2 }
                ]
            },
          
            {
                type: "spline",
                axisYType: "secondary",
                name: "Distance Covered",
                dataPoints: [
                { x: 1, y: 2  },
                { x: 2, y: 2 },
                { x: 3, y: 1 },
                { x: 4, y: 2},
                { x: 5, y: 2},
                { x: 6, y: 3},
                { x: 7, y: 1},
                { x: 8, y: 2 },
                { x: 9, y:  2 },
                { x: 10, y:  1},
                { x: 11, y:  3},

                { x: 12, y:  2 }
                ]
            }
            ]
        });

        chart3.render();
    }
</script>
<script type="text/javascript" src="~/Scripts/canvasjs.min.js"></script>



@*<div id="chartContainer3"></div>*@

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<br />
<br />
<table class="table table-hover" style="margin-top:50px">
    <caption class="display-caption" style="text-align:center;">
        Previous Evaluations
    </caption>
    <thead style="border-bottom:ridge; border-color:#266f91">
        <tr>
            <th style="padding-top: 2em">
                @*@Html.DisplayNameFor(model => model.StoredRole.RoleName)*@
                <span class="display-header"> <strong>Rating</strong> </span>
            </th>
            <th style="padding-top: 2em">
                @*@Html.DisplayNameFor(model => model.SystemUser.LastName)*@
                <span class="display-header"> <strong>Evaluation Date</strong> </span>
            </th>
            <th style="padding-top: 2em">
                @*@Html.DisplayNameFor(model => model.SystemUser.LastName)*@
                <span class="display-header"> <strong>Complete Objectives</strong> </span>
            </th>
            <th style="padding-top: 2em">
                @*@Html.DisplayNameFor(model => model.SystemUser.LastName)*@
                <span class="display-header"> <strong>Total Objectives</strong> </span>
            </th>
            <th style="padding-top: 2em">
                @*@Html.DisplayNameFor(model => model.SystemUser.LastName)*@
                <span class="display-header"> <strong>Manager Comment</strong> </span>
            </th>
            <th style="padding-top: 2em">
                @*@Html.DisplayNameFor(model => model.SystemUser.LastName)*@
                <span class="display-header"> <strong>Employee Comment</strong> </span>
            </th>
            <th></th>
        </tr>
    </thead>
    @*<tr>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EvaluationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompleteObjectives)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalObjectives)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManagerComment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeComment)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.SystemUser.LastName)
        </th>*@
    @*<th></th>*@
    @*</tr>*@
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EvaluationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompleteObjectives)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalObjectives)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManagerComment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeComment)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.SystemUser.LastName)
                </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.EvaluationID }) |
                @Html.ActionLink("Details", "Details", new { id = item.EvaluationID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.EvaluationID })
            </td>
        </tr>
    }
</table>
<div>
    @*<button class="btn btn-searching" style="margin-bottom:10px; margin-left:10px; color:white; background-color:#266f91; border:none; padding:5px; border-radius:2px;" onclick="location.href='@Url.Action("SelectedEmployee", "Goals", new { id = @ViewBag.EvalID })'">Back to Employee Page</button>*@
    <button class="btn btn-searching" style="margin-bottom:10px; margin-left:10px; color:white; background-color:#266f91; border:none; padding:5px; border-radius:2px;" onclick="location.href='@Url.Action("ManagerEmployees", "SystemUsers", new { id = @ViewBag.AssignedManagerID })'">Back to Dashboard</button>
</div>